### PR TITLE
adding tween.js delay option support

### PR DESCRIPTION
**Pull request by shenoy**
This allows doing things like staggering animations as in this example https://codesandbox.io/s/7w0lww2l40

Not sure if I should run tests for this? Got an error related to localStorage when I tried.

### CODE REVIEW

**Comment by posva** [comment]
Hey! Thanks for this! 
Tests failing are related to jest. I will update deps and fix it but Yeah, please add a test 😄

**Comment by posva** [comment]
They are fixed, you should be able to rebase against master now :)

**Comment by shenoy** [comment]
Hey @posva , could you please check if this is okay and advise?  Unsure if I've gone wrong with 
1. how to include my additions into the code coverage
2. commits ending up on this pull request 😨

**Comment by posva** [comment]
Maybe you did a merge 😅 
I did a rebase against master and push forced to your branch

**Pull request merged**
